modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/KiroTheBlueFox/MoBlocks/issues"

[[mods]]
modId="moblocks"
version="1.0"
displayName="Mo'Blocks"
#updateJSONURL="" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/moblocks"
logoFile="icon512.png"
credits="Credits goes to KiroTheBlueFox (Mod) & Hypherion (Colored Light API), Mysticpasta1 for continuing my mod"
authors="KiroTheBlueFox, HypherionSA, Mysticpasta1"
description='''
Mo'Blocks is a simple mod that adds random decorative and useful blocks.
'''

[[dependencies.moblocks]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
